### ISSUE TITLE
Looking for `Queue` helper

### ISSUE THREAD

**Issue by ryanlabouve** [EmberSherpa/ember-reactive-helpers#13]
I'm looking for a helper, similar to pipe, that would pass the same arguments to all given actions

e.g.:
```
<input 
  onchange={{action (queue (action 'showAddressOnMap') 
                           (action (mut address))) value="target.value"}} />
```

I stumbled on this issue and I would be happy to help implement this you are still interested: https://github.com/DockYard/ember-composable-helpers/pull/134

**Comment by taras** [comment]
@ryanlabouve welcome your PR for this :)

**Comment by taras** [comment]
`queue` helper is now available in `ember-composable-helpers`
