### ISSUE TITLE
Blank Demo Page

### ISSUE THREAD

**Issue by ryanlabouve** [EmberSherpa/ember-reactive-helpers#20]
Just looking around for ways to help and I noticed the demo page was blank. Do you have any plans for this? 

If you can outline what you'd like to see I don't mind working on it a bit.

Thanks, and if there is anything else I can help with on this repo please tag me. I have some OSS availability for the next few months and would love to help here if you're looking for anything.

**Comment by tzellman** [comment]
I added links to the 3 defined routes in the dummy app. Should be good to go now. Whatup man?
