### ISSUE TITLE
Transition To helper within Ember Engines looks outside the engine

### ISSUE THREAD

**Issue by devotox** [EmberSherpa/ember-reactive-helpers#22]
I would think the transition to helper for an in app engine would be confined to its own boundaries

**Comment by taras** [comment]
PR is welcome :)

-- 
Taras Mankovski

**Comment by devotox** [comment]
Thanks for the quick reply. 

I just looked into it and I guess for your information as well it seems that the Ember Engine itself does not have a routing service and thus this transitionTo helper works as it should

https://github.com/ember-engines/ember-engines/issues/260

When I do use the full path it works right. I am wondering now if there is something possibly clever that can be done that sees if you are inside an engine and adds the initial path for you.... but then again is it worth it?

Anyways closing this and thank you
